# Generated by Django 4.1.4 on 2023-01-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                ("no", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
                ("price", models.FloatField()),
                ("quantity", models.IntegerField()),
                ("description", models.TextField()),
            ],
        ),
    ]
